apiVersion: v1
kind: Service
metadata:
  name: bookslib-service
  namespace: default
  labels:
    app: bookslib
spec:
  type: NodePort
  selector:
    app: bookslib
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
